### ISSUE TITLE
genetic data

### ISSUE THREAD

**Issue by Camelus-to** [ManojKumar002/multimodal_alzheimer_detection#1]
Hello author, I am working with genetic data, filter_vcfs.py,
start = vcf_file.find("ADNI_ID.") + len("ADNI_ID.")
end = vcf_file.find("output.vcf")
For the genetic data in ANDI dataset, do you use.plink files for genetic data processing or.vCF files? I can't find the string ADNI_ID. Did you name these by yourself? Thank you for your answer

**Comment by ManojKumar002** [comment]
Hi,
For genetic we have used the data which is in .vcf file format.
We got this data from ADNI website (https://ida.loni.usc.edu/pages/access/geneticData.jsp?project=ADNI&page=DOWNLOADS&subPage=GENETIC_DATA).
To be specific , the name of the files which we have used looks like this "[ADNI WGS Data - GATK SNV+Indel call chr15 of 23]"
