### ISSUE TITLE
about MRI data

### ISSUE THREAD

**Issue by shuilinggirl** [ManojKumar002/multimodal_alzheimer_detection#2]
hi, I would like to inquire about the name of your MRI dataset in the ADNI database. If possible, could you provide me with a download website for the MRI dataset

**Comment by ManojKumar002** [comment]
Hi,
You can find the image data in the website mentioned below. However, you need to have an account to access these data.

https://ida.loni.usc.edu/pages/access/search.jsp?tab=collection&project=ADNI&page=DOWNLOADS&subPage=IMAGE_COLLECTIONS
