### ISSUE TITLE
About image acc

### ISSUE THREAD

**Issue by shuilinggirl** [ManojKumar002/multimodal_alzheimer_detection#3]
Hello, I'd like to inquire about the accuracy you achieved on the single-modal Image data. I'm having trouble reproducing the results from Michal's paper. Additionally, I already have access to the ADNI dataset, and I'm curious about how you selected your image_collections.

**Comment by ManojKumar002** [comment]
Hi 
We got an accuracy of 48.8% for single-modal MRI image data with 50 epochs and a learning rate of 0.001.

We have filtering the images on ADNI website using the following criteria :
```
Projects : ADNI,ADNI1,ADNIGO,ADNI2
Age : <76 and <79
Research group : MCI,CN,AD
Weighting : T1
```
